[package]
name = "rust-envsys"
version = "0.1.0"
authors = ["Thomas Klausner <tk@giga.or.at>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "*"
plist = "*"
